/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JokerStoreClerk;

import java.awt.Color;
import java.awt.Container;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import listeners.SelectClient_AddClient_BT_NewClient_Listeners;
import listeners.SelectClient_Search_BT_ExistingClient_Listener;
import listeners.SelectClient_Select_BT_ExistingClient_Listener;

/**
 *
 * @author JOHN
 */
public class SelectClient extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    public SelectClient() {

        initComponents();
        Container a = this.getContentPane();
        a.setBackground(Color.WHITE);

        //Add all listener classes
        Search_BT_ExistingClient.addActionListener(new SelectClient_Search_BT_ExistingClient_Listener(this));
        Select_BT_ExistingClient.addActionListener(new SelectClient_Select_BT_ExistingClient_Listener(this));
        AddClient_BT_NewClient.addActionListener(new SelectClient_AddClient_BT_NewClient_Listeners(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserCategory_BG = new javax.swing.ButtonGroup();
        TabbedPane = new javax.swing.JTabbedPane();
        ExistingClient_Panel = new javax.swing.JPanel();
        Select_BT_ExistingClient = new javax.swing.JButton();
        ClientID_TF_ExistigCliet = new javax.swing.JTextField();
        ClientID_LB_ExistingClient = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Client_Table_ExistingClient = new javax.swing.JTable();
        SearchName_LB_ExistingClient = new javax.swing.JLabel();
        SearchName_TF_ExistigCliet = new javax.swing.JTextField();
        Search_BT_ExistingClient = new javax.swing.JButton();
        Register_Panel = new javax.swing.JPanel();
        Name_LB_NewClient = new javax.swing.JLabel();
        Address_LB_NewClient = new javax.swing.JLabel();
        AddClient_BT_NewClient = new javax.swing.JButton();
        Name_TF_NewClient = new javax.swing.JTextField();
        Address_TF_NewClient = new javax.swing.JTextField();
        Logo1 = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();
        Logo3 = new javax.swing.JLabel();
        Welcome_LB_Login1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 700));
        setResizable(false);

        TabbedPane.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        ExistingClient_Panel.setBackground(new java.awt.Color(245, 245, 245));

        Select_BT_ExistingClient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Select_BT_ExistingClient.setForeground(new java.awt.Color(102, 102, 102));
        Select_BT_ExistingClient.setText("Select");
        Select_BT_ExistingClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select_BT_ExistingClientActionPerformed(evt);
            }
        });

        ClientID_TF_ExistigCliet.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        ClientID_LB_ExistingClient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ClientID_LB_ExistingClient.setText("Client ID");

        Client_Table_ExistingClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Client_Table_ExistingClient);
        if (Client_Table_ExistingClient.getColumnModel().getColumnCount() > 0) {
            Client_Table_ExistingClient.getColumnModel().getColumn(0).setResizable(false);
            Client_Table_ExistingClient.getColumnModel().getColumn(1).setResizable(false);
            Client_Table_ExistingClient.getColumnModel().getColumn(2).setResizable(false);
        }

        SearchName_LB_ExistingClient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        SearchName_LB_ExistingClient.setText("Search Name");

        SearchName_TF_ExistigCliet.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        Search_BT_ExistingClient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Search_BT_ExistingClient.setForeground(new java.awt.Color(102, 102, 102));
        Search_BT_ExistingClient.setText("Search");
        Search_BT_ExistingClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_BT_ExistingClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExistingClient_PanelLayout = new javax.swing.GroupLayout(ExistingClient_Panel);
        ExistingClient_Panel.setLayout(ExistingClient_PanelLayout);
        ExistingClient_PanelLayout.setHorizontalGroup(
            ExistingClient_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExistingClient_PanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ExistingClient_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ExistingClient_PanelLayout.createSequentialGroup()
                        .addComponent(SearchName_LB_ExistingClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchName_TF_ExistigCliet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_BT_ExistingClient, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ExistingClient_PanelLayout.createSequentialGroup()
                        .addComponent(ClientID_LB_ExistingClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClientID_TF_ExistigCliet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Select_BT_ExistingClient))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        ExistingClient_PanelLayout.setVerticalGroup(
            ExistingClient_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExistingClient_PanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(ExistingClient_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchName_TF_ExistigCliet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchName_LB_ExistingClient)
                    .addComponent(Search_BT_ExistingClient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ExistingClient_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClientID_TF_ExistigCliet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClientID_LB_ExistingClient)
                    .addComponent(Select_BT_ExistingClient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        TabbedPane.addTab("Existing Client", ExistingClient_Panel);

        Register_Panel.setBackground(new java.awt.Color(245, 245, 245));

        Name_LB_NewClient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Name_LB_NewClient.setText("Name");

        Address_LB_NewClient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Address_LB_NewClient.setText("Address");

        AddClient_BT_NewClient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AddClient_BT_NewClient.setText("Add Client");
        AddClient_BT_NewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClient_BT_NewClientActionPerformed(evt);
            }
        });

        Name_TF_NewClient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Name_TF_NewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_TF_NewClientActionPerformed(evt);
            }
        });

        Address_TF_NewClient.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout Register_PanelLayout = new javax.swing.GroupLayout(Register_Panel);
        Register_Panel.setLayout(Register_PanelLayout);
        Register_PanelLayout.setHorizontalGroup(
            Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Register_PanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Name_LB_NewClient)
                    .addComponent(Address_LB_NewClient))
                .addGap(18, 18, 18)
                .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddClient_BT_NewClient, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(Name_TF_NewClient)
                    .addComponent(Address_TF_NewClient))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        Register_PanelLayout.setVerticalGroup(
            Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Register_PanelLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_LB_NewClient)
                    .addComponent(Name_TF_NewClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address_LB_NewClient)
                    .addComponent(Address_TF_NewClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddClient_BT_NewClient)
                .addGap(343, 343, 343))
        );

        TabbedPane.addTab("New Client", Register_Panel);

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokerStoreClerk/JokerLogo1.png"))); // NOI18N

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokerStoreClerk/JokerLogo2.png"))); // NOI18N

        Logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokerStoreClerk/JokerLogo3.png"))); // NOI18N

        Welcome_LB_Login1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Welcome_LB_Login1.setForeground(new java.awt.Color(102, 102, 102));
        Welcome_LB_Login1.setText("Select Client");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TabbedPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Logo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Logo2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Logo3)
                            .addComponent(Welcome_LB_Login1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Logo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo2)
                    .addComponent(Logo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Welcome_LB_Login1)
                .addGap(18, 18, 18)
                .addComponent(TabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Select_BT_ExistingClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select_BT_ExistingClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Select_BT_ExistingClientActionPerformed

    private void AddClient_BT_NewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClient_BT_NewClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddClient_BT_NewClientActionPerformed

    private void Name_TF_NewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_TF_NewClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TF_NewClientActionPerformed

    private void Search_BT_ExistingClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_BT_ExistingClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_BT_ExistingClientActionPerformed

    public void showMsg(String text) {
        JOptionPane.showMessageDialog(null, text);
    }

    public JButton getAddClient_BT_NewClient() {
        return AddClient_BT_NewClient;
    }

    public JLabel getAddress_LB_NewClient() {
        return Address_LB_NewClient;
    }

    public JTextField getAddress_TF_NewClient() {
        return Address_TF_NewClient;
    }

    public JLabel getClientID_LB_ExistingClient() {
        return ClientID_LB_ExistingClient;
    }

    public JTextField getClientID_TF_ExistigCliet() {
        return ClientID_TF_ExistigCliet;
    }

    public JTable getClient_Table_ExistingClient() {
        return Client_Table_ExistingClient;
    }

    public JPanel getExistingClient_Panel() {
        return ExistingClient_Panel;
    }

    public JLabel getLogo1() {
        return Logo1;
    }

    public JLabel getLogo2() {
        return Logo2;
    }

    public JLabel getLogo3() {
        return Logo3;
    }

    public JLabel getName_LB_NewClient() {
        return Name_LB_NewClient;
    }

    public JTextField getName_TF_NewClient() {
        return Name_TF_NewClient;
    }

    public JPanel getRegister_Panel() {
        return Register_Panel;
    }

    public JLabel getSearchName_LB_ExistingClient() {
        return SearchName_LB_ExistingClient;
    }

    public JTextField getSearchName_TF_ExistigCliet() {
        return SearchName_TF_ExistigCliet;
    }

    public JButton getSearch_BT_ExistingClient() {
        return Search_BT_ExistingClient;
    }

    public JButton getSelect_BT_ExistingClient() {
        return Select_BT_ExistingClient;
    }

    public JTabbedPane getTabbedPane() {
        return TabbedPane;
    }

    public ButtonGroup getUserCategory_BG() {
        return UserCategory_BG;
    }

    public JLabel getWelcome_LB_Login1() {
        return Welcome_LB_Login1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClient_BT_NewClient;
    private javax.swing.JLabel Address_LB_NewClient;
    private javax.swing.JTextField Address_TF_NewClient;
    private javax.swing.JLabel ClientID_LB_ExistingClient;
    private javax.swing.JTextField ClientID_TF_ExistigCliet;
    private javax.swing.JTable Client_Table_ExistingClient;
    private javax.swing.JPanel ExistingClient_Panel;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel Logo3;
    private javax.swing.JLabel Name_LB_NewClient;
    private javax.swing.JTextField Name_TF_NewClient;
    private javax.swing.JPanel Register_Panel;
    private javax.swing.JLabel SearchName_LB_ExistingClient;
    private javax.swing.JTextField SearchName_TF_ExistigCliet;
    private javax.swing.JButton Search_BT_ExistingClient;
    private javax.swing.JButton Select_BT_ExistingClient;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.ButtonGroup UserCategory_BG;
    private javax.swing.JLabel Welcome_LB_Login1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
