/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JokerStoreClerk;

import java.awt.Color;
import java.awt.Container;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import listeners.WelcomePage_Login_BT_Login_Listener;

/**
 *
 * @author JOHN
 */
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {

        initComponents();
        Container a = this.getContentPane();
        a.setBackground(Color.WHITE);

        //Add all listener classes
        Login_BT_Login.addActionListener(new WelcomePage_Login_BT_Login_Listener(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        Login_Panel = new javax.swing.JPanel();
        ClerkName_LB_Login = new javax.swing.JLabel();
        Password_LB_Login = new javax.swing.JLabel();
        ClerkName_TF_Login = new javax.swing.JTextField();
        Password_TF_Login = new javax.swing.JTextField();
        Login_BT_Login = new javax.swing.JButton();
        Welcome_LB_Login = new javax.swing.JLabel();
        Logo1 = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();
        Logo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 700));
        setResizable(false);

        TabbedPane.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        Login_Panel.setBackground(new java.awt.Color(245, 245, 245));

        ClerkName_LB_Login.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ClerkName_LB_Login.setText("Clerk Name");

        Password_LB_Login.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Password_LB_Login.setText("Password");

        ClerkName_TF_Login.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ClerkName_TF_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClerkName_TF_LoginActionPerformed(evt);
            }
        });

        Password_TF_Login.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        Login_BT_Login.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Login_BT_Login.setText("Log In");
        Login_BT_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_BT_LoginActionPerformed(evt);
            }
        });

        Welcome_LB_Login.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        Welcome_LB_Login.setForeground(new java.awt.Color(102, 102, 102));
        Welcome_LB_Login.setText("Welcome   :) ");

        javax.swing.GroupLayout Login_PanelLayout = new javax.swing.GroupLayout(Login_Panel);
        Login_Panel.setLayout(Login_PanelLayout);
        Login_PanelLayout.setHorizontalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_PanelLayout.createSequentialGroup()
                .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Login_PanelLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(Login_BT_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Login_PanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password_LB_Login, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ClerkName_LB_Login, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClerkName_TF_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password_TF_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Login_PanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Welcome_LB_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        Login_PanelLayout.setVerticalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_PanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Welcome_LB_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClerkName_LB_Login)
                    .addComponent(ClerkName_TF_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_LB_Login)
                    .addComponent(Password_TF_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(Login_BT_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabbedPane.addTab("Log In  ", Login_Panel);

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokerStoreClerk/JokerLogo1.png"))); // NOI18N

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokerStoreClerk/JokerLogo2.png"))); // NOI18N

        Logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JokerStoreClerk/JokerLogo3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TabbedPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Logo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Logo2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Logo3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Logo3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Logo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logo1)
                        .addGap(18, 18, 18)))
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClerkName_TF_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClerkName_TF_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClerkName_TF_LoginActionPerformed

    private void Login_BT_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_BT_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_BT_LoginActionPerformed

    public void showMsg(String text) {
        JOptionPane.showMessageDialog(null, text);
    }

    public JLabel getClerkName_LB_Login() {
        return ClerkName_LB_Login;
    }

    public JTextField getClerkName_TF_Login() {
        return ClerkName_TF_Login;
    }

    public JButton getLogin_BT_Login() {
        return Login_BT_Login;
    }

    public JPanel getLogin_Panel() {
        return Login_Panel;
    }

    public JLabel getLogo1() {
        return Logo1;
    }

    public JLabel getLogo2() {
        return Logo2;
    }

    public JLabel getLogo3() {
        return Logo3;
    }

    public JLabel getPassword_LB_Login() {
        return Password_LB_Login;
    }

    public JTextField getPassword_TF_Login() {
        return Password_TF_Login;
    }

    public JTabbedPane getTabbedPane() {
        return TabbedPane;
    }

    public JLabel getWelcome_LB_Login() {
        return Welcome_LB_Login;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClerkName_LB_Login;
    private javax.swing.JTextField ClerkName_TF_Login;
    private javax.swing.JButton Login_BT_Login;
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel Logo3;
    private javax.swing.JLabel Password_LB_Login;
    private javax.swing.JTextField Password_TF_Login;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel Welcome_LB_Login;
    // End of variables declaration//GEN-END:variables
}
